#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUNDLE="$ROOT/nexashop-refactor"

if [ ! -f "$ROOT/package.json" ]; then echo "Jalankan dari bundle yang ditempatkan di repository root."; exit 1; fi

mkdir -p "$ROOT/$(dirname "src/lib/auth.ts")"
cp "$BUNDLE/src/lib/auth.ts" "$ROOT/src/lib/auth.ts"
mkdir -p "$ROOT/$(dirname "src/lib/api.ts")"
cp "$BUNDLE/src/lib/api.ts" "$ROOT/src/lib/api.ts"
mkdir -p "$ROOT/$(dirname "src/schemas/product-schema.ts")"
cp "$BUNDLE/src/schemas/product-schema.ts" "$ROOT/src/schemas/product-schema.ts"
mkdir -p "$ROOT/$(dirname "src/types/product.ts")"
cp "$BUNDLE/src/types/product.ts" "$ROOT/src/types/product.ts"
mkdir -p "$ROOT/$(dirname "src/stores/product-store.ts")"
cp "$BUNDLE/src/stores/product-store.ts" "$ROOT/src/stores/product-store.ts"
mkdir -p "$ROOT/$(dirname "src/app/api/products/route.ts")"
cp "$BUNDLE/src/app/api/products/route.ts" "$ROOT/src/app/api/products/route.ts"
mkdir -p "$ROOT/$(dirname "src/app/api/products/[id]/route.ts")"
cp "$BUNDLE/src/app/api/products/[id]/route.ts" "$ROOT/src/app/api/products/[id]/route.ts"
mkdir -p "$ROOT/$(dirname "src/app/layout.tsx")"
cp "$BUNDLE/src/app/layout.tsx" "$ROOT/src/app/layout.tsx"
mkdir -p "$ROOT/$(dirname "src/app/(admin)/admin/layout.tsx")"
cp "$BUNDLE/src/app/(admin)/admin/layout.tsx" "$ROOT/src/app/(admin)/admin/layout.tsx"
mkdir -p "$ROOT/$(dirname "src/app/(admin)/admin/AdminShell.tsx")"
cp "$BUNDLE/src/app/(admin)/admin/AdminShell.tsx" "$ROOT/src/app/(admin)/admin/AdminShell.tsx"
mkdir -p "$ROOT/$(dirname "src/app/(admin)/admin/page.tsx")"
cp "$BUNDLE/src/app/(admin)/admin/page.tsx" "$ROOT/src/app/(admin)/admin/page.tsx"
mkdir -p "$ROOT/$(dirname "src/app/(admin)/admin/products/page.tsx")"
cp "$BUNDLE/src/app/(admin)/admin/products/page.tsx" "$ROOT/src/app/(admin)/admin/products/page.tsx"
mkdir -p "$ROOT/$(dirname "src/app/auth/redirect/page.tsx")"
cp "$BUNDLE/src/app/auth/redirect/page.tsx" "$ROOT/src/app/auth/redirect/page.tsx"
mkdir -p "$ROOT/$(dirname "src/app/(auth)/sign-in/[[...sign-in]]/page.tsx")"
cp "$BUNDLE/src/app/(auth)/sign-in/[[...sign-in]]/page.tsx" "$ROOT/src/app/(auth)/sign-in/[[...sign-in]]/page.tsx"
mkdir -p "$ROOT/$(dirname "src/app/(auth)/sign-up/[[...sign-up]]/page.tsx")"
cp "$BUNDLE/src/app/(auth)/sign-up/[[...sign-up]]/page.tsx" "$ROOT/src/app/(auth)/sign-up/[[...sign-up]]/page.tsx"
mkdir -p "$ROOT/$(dirname "src/proxy.ts")"
cp "$BUNDLE/src/proxy.ts" "$ROOT/src/proxy.ts"
rm -rf "$ROOT/src/app/sign-in" "$ROOT/src/app/sign-up"
rm -f "$ROOT/src/context/CartContext.tsx"
echo "Refactor core diterapkan."
echo "Berikutnya: npm install && npm run db:generate && npm run lint && npm run build"